services:
  - type: web
    name: MIMI-TOV-ASSISTANT
    env: node
    buildCommand: "npm install"
    startCommand: "node index.js"
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_ADMIN_ID
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: SAVE_MEDIA
        value: "false"
      - key: WA_PHONE_NUMBER
        sync: false